// Guards two cross-file pins that are documented and otherwise unenforced.
//
// Both share a failure shape: they cannot go wrong at compile time, they cannot
// go wrong in `flutter analyze`, and they only surface in a browser — which in
// this repo means the web lane or a visitor, not the developer who moved the
// pin. AGENTS.md § 4 records the frb one costing "an empty `Uncaught` before
// pkg/oxidant.js loaded", and project-operations.md's write-up of it ends with
// "**Prevention:** Always regenerate bindings" — a human rule that has already
// failed once. This is that rule, executable.
//
// Pure dart:io, no rootBundle and no Flutter binding, so it runs anywhere
// `flutter test` runs. Paths resolve from the test's own location rather than
// the CWD, because the container runs it from /workspace and a developer may
// not.

import 'dart:io';

import 'package:crypto/crypto.dart';
import 'package:flutter_test/flutter_test.dart';

/// Repo root, found by walking up from this file until pubspec.yaml appears.
Directory _repoRoot() {
  Directory dir = File.fromUri(Platform.script).parent;
  if (!File('${dir.path}/pubspec.yaml').existsSync()) {
    dir = Directory.current;
  }
  while (!File('${dir.path}/pubspec.yaml').existsSync()) {
    final Directory parent = dir.parent;
    if (parent.path == dir.path) {
      fail('could not find the repo root (no pubspec.yaml on the way up)');
    }
    dir = parent;
  }
  return dir;
}

String _read(String relative) {
  final File file = File('${_repoRoot().path}/$relative');
  if (!file.existsSync()) fail('missing file: $relative');
  return file.readAsStringSync();
}

/// First capture group of [pattern] in [relative], or a failure naming both.
String _extract(String relative, RegExp pattern, String what) {
  final RegExpMatch? match = pattern.firstMatch(_read(relative));
  if (match == null) {
    fail(
      'could not find $what in $relative — the pin moved or the file was '
      'restructured, so this test can no longer check it. Fix the pattern, do '
      'not delete the test.',
    );
  }
  return match.group(1)!;
}

void main() {
  group('flutter_rust_bridge version pins agree', () {
    // The Rust side is the source of truth: it is an exact `=` pin, and the
    // generated Dart is written by the codegen that matches it.
    late final String rustPin = _extract(
      'third_party/OxidANT/Cargo.toml',
      RegExp(r'^flutter_rust_bridge\s*=\s*"=([\d.]+)"', multiLine: true),
      'the flutter_rust_bridge = "=x.y.z" workspace pin',
    );

    test('the committed bindings were generated by the pinned codegen', () {
      final String codegen = _extract(
        'lib/src/rust/frb_generated.dart',
        RegExp(r"String get codegenVersion => '([\d.]+)'"),
        'codegenVersion',
      );
      expect(
        codegen,
        rustPin,
        reason:
            'lib/src/rust/ was generated by flutter_rust_bridge_codegen '
            '$codegen but third_party/OxidANT/Cargo.toml pins the runtime to '
            '$rustPin. The web build fails with an empty "Uncaught" before '
            'pkg/oxidant.js loads. Regenerate BOTH sides together: '
            '`flutter_rust_bridge_codegen generate`.',
      );
    });

    test('the pubspec constraint admits the pinned version', () {
      final String constraint = _extract(
        'pubspec.yaml',
        RegExp(r'^\s+flutter_rust_bridge:\s*\^?([\d.]+)', multiLine: true),
        'the flutter_rust_bridge dependency constraint',
      );

      final List<int> floor = constraint
          .split('.')
          .map((String p) => int.parse(p))
          .toList();
      final List<int> pinned = rustPin
          .split('.')
          .map((String p) => int.parse(p))
          .toList();

      expect(
        floor[0],
        pinned[0],
        reason: 'major mismatch: pubspec ^$constraint vs Rust $rustPin',
      );
      // A caret floor BELOW the Rust pin resolves to the right version today
      // only by luck of what else is in the lock. It must be at least the pin.
      expect(
        floor[1],
        greaterThanOrEqualTo(pinned[1]),
        reason:
            'pubspec.yaml allows flutter_rust_bridge ^$constraint while the '
            'Rust runtime is pinned to $rustPin. Raise the caret floor to '
            '^$rustPin so a resolve cannot pick a Dart runtime older than the '
            'generated bindings expect.',
      );
    });
  });

  group('committed web binaries match their upstream pin', () {
    test('web/sqlite3.wasm is the build ANTfrastructure records', () {
      // web/sqlite3.wasm is committed (0.7 MB) rather than fetched at build
      // time, so nothing re-verifies it. Upstream pins the release it came
      // from, which makes drift checkable for free.
      final String expected = _extract(
        'third_party/ANTfrastructure/linux/scripts/01-core/versions.env',
        RegExp(r'^SQLITE3_WASM_SHA256=([0-9a-f]{64})', multiLine: true),
        'SQLITE3_WASM_SHA256',
      );
      final String actual = sha256
          .convert(
            File('${_repoRoot().path}/web/sqlite3.wasm').readAsBytesSync(),
          )
          .toString();
      expect(
        actual,
        expected,
        reason:
            'web/sqlite3.wasm does not match SQLITE3_WASM_SHA256 in the pinned '
            'ANTfrastructure. Either the submodule moved to a new sqlite3 '
            'release and web/sqlite3.wasm was not refreshed, or the committed '
            'binary was replaced by hand. Refresh it with '
            'linux/scripts/05-frameworks/flutter/setup-sqlite3-wasm.sh.',
      );
    });
  });
}
