// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `detect_persons_rgba_impl`

List<Detection> detectPersonsRgba({
  required String modelPath,
  required List<int> rgba,
  required int width,
  required int height,
  required double scoreThreshold,
}) => RustLib.instance.api.crateApiOnnxDetectPersonsRgba(
  modelPath: modelPath,
  rgba: rgba,
  width: width,
  height: height,
  scoreThreshold: scoreThreshold,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Detection>>
abstract class Detection implements RustOpaqueInterface {}
