// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// Forwarding shim for platform-specific initialization.
/// The real implementation lives in `crate::platform` (wasm/native).
Future<void> initApp() => RustLib.instance.api.crateApiSimpleInitApp();

/// Synchronous heavy computation demo (template stub).
int heavyComputation({required int input}) =>
    RustLib.instance.api.crateApiSimpleHeavyComputation(input: input);

/// Asynchronous work demo (template stub).
Future<int> asyncHeavyWork({required int input}) =>
    RustLib.instance.api.crateApiSimpleAsyncHeavyWork(input: input);
