// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

List<CameraDesc> listCameras() =>
    RustLib.instance.api.crateApiWebcamListCameras();

/// Starts capture + inference; events arrive on `sink` until
/// [`stop_webcam_inference`] is called. Errors if already running.
Stream<DetectionEvent> startWebcamInference({
  required WebcamStreamConfig config,
}) => RustLib.instance.api.crateApiWebcamStartWebcamInference(config: config);

/// Stops the running session (no-op when idle).
void stopWebcamInference() =>
    RustLib.instance.api.crateApiWebcamStopWebcamInference();

class CameraDesc {
  final int index;
  final String name;

  const CameraDesc({required this.index, required this.name});

  @override
  int get hashCode => index.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CameraDesc &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          name == other.name;
}

/// A detection in source-frame pixel coordinates. Field-accessible Dart
/// mirror of `kataglyphis_core::detection::Detection` (which the bridge
/// would otherwise expose as an opaque type).
class DetectionBox {
  final double x1;
  final double y1;
  final double x2;
  final double y2;
  final double score;
  final PlatformInt64 classId;

  const DetectionBox({
    required this.x1,
    required this.y1,
    required this.x2,
    required this.y2,
    required this.score,
    required this.classId,
  });

  @override
  int get hashCode =>
      x1.hashCode ^
      y1.hashCode ^
      x2.hashCode ^
      y2.hashCode ^
      score.hashCode ^
      classId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DetectionBox &&
          runtimeType == other.runtimeType &&
          x1 == other.x1 &&
          y1 == other.y1 &&
          x2 == other.x2 &&
          y2 == other.y2 &&
          score == other.score &&
          classId == other.classId;
}

class DetectionEvent {
  final List<DetectionBox> detections;
  final BigInt frameSequence;
  final BigInt? ptsMs;
  final double inferenceMs;
  final double fps;

  const DetectionEvent({
    required this.detections,
    required this.frameSequence,
    this.ptsMs,
    required this.inferenceMs,
    required this.fps,
  });

  @override
  int get hashCode =>
      detections.hashCode ^
      frameSequence.hashCode ^
      ptsMs.hashCode ^
      inferenceMs.hashCode ^
      fps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DetectionEvent &&
          runtimeType == other.runtimeType &&
          detections == other.detections &&
          frameSequence == other.frameSequence &&
          ptsMs == other.ptsMs &&
          inferenceMs == other.inferenceMs &&
          fps == other.fps;
}

class WebcamStreamConfig {
  /// `videotestsrc` instead of a real camera (containers/CI have none).
  final bool useTestSource;

  /// Camera enumeration index; `None` = first available.
  final int? deviceIndex;
  final int width;
  final int height;
  final int framerate;
  final String modelPath;
  final double scoreThreshold;

  /// Texture id from the native plugin's `create` call; `0` = headless.
  final PlatformInt64 textureId;

  /// Override for the DLL exporting `knt_push_frame`.
  final String? textureLibrary;

  const WebcamStreamConfig({
    required this.useTestSource,
    this.deviceIndex,
    required this.width,
    required this.height,
    required this.framerate,
    required this.modelPath,
    required this.scoreThreshold,
    required this.textureId,
    this.textureLibrary,
  });

  @override
  int get hashCode =>
      useTestSource.hashCode ^
      deviceIndex.hashCode ^
      width.hashCode ^
      height.hashCode ^
      framerate.hashCode ^
      modelPath.hashCode ^
      scoreThreshold.hashCode ^
      textureId.hashCode ^
      textureLibrary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebcamStreamConfig &&
          runtimeType == other.runtimeType &&
          useTestSource == other.useTestSource &&
          deviceIndex == other.deviceIndex &&
          width == other.width &&
          height == other.height &&
          framerate == other.framerate &&
          modelPath == other.modelPath &&
          scoreThreshold == other.scoreThreshold &&
          textureId == other.textureId &&
          textureLibrary == other.textureLibrary;
}
